name: Build CKAN Docker 

on:
  # Trigger the workflow on push or pull request,
  # but only for the prod-demo branch
  push:
    branches:
      - prod-demo
  pull_request:
    branches:
      - prod-demo

jobs: 
  build:  
    runs-on: ubuntu-latest
    steps: 
    -  uses: actions/checkout@v2

    -  name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
       with:
          driver: docker # defaults to "docker-containerized"
      
    -  name: Set up QEMU
       uses: docker/setup-qemu-action@v1

    -  name: NGINX build
       uses: docker/build-push-action@v2
       with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: false
          tags: kowhai/ckan-docker-nginx:test-build-only

    -  name: PostgreSQL build
       uses: docker/build-push-action@v2
       with:
          context: ./postgresql
          file: ./postgresql/Dockerfile
          push: false
          tags: kowhai/ckan-docker-postgresql:test-build-only

    -  name: maintenance Build
       uses: docker/build-push-action@v2
       with:
          context: ./maintenance
          file: ./maintenance/Dockerfile
          push: false
          tags: kowhai/ckan-docker-ckan:test-build-only

    -  name: Clone ckan-base
       uses: actions/checkout@v4
       with:
          repository: depositar/ckan-docker-base
          path: ckan-docker-base

    - name: Read version from VERSION file
      run: |
         VERSION_VALUE=$(cat "ckan-docker-base/ckan-depositar/VERSION.txt")
         echo "Using ref $VERSION_VALUE in next steps"
         echo "CKAN_REF=$VERSION_VALUE" >> $GITHUB_ENV

    -  name: Build the ckan-base image
       uses: docker/build-push-action@v2
       with:
          context: ./ckan-docker-base/ckan-depositar
          push: false
          build-args: |
            CKAN_REF=${{ env.CKAN_REF }}
            ENV=base
          tags: |
            depositar/ckan-base:release-data-depositar-io-py3.10

    -  name: CKAN build
       uses: docker/build-push-action@v2
       with:
          context: ./ckan
          file: ./ckan/Dockerfile
          push: false
          tags: kowhai/ckan-docker-ckan:test-build-only
      